Search.appendIndex(
    [
                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\Bus",
            "name": "Bus",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-Bus.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\Bus\u003A\u003AexecuteCommand\u0028\u0029",
            "name": "executeCommand",
            "summary": "Send\u0020and\u0020execute\u0020command\u0020synchronously",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-Bus.html#method_executeCommand"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\Bus\u003A\u003AsendCommand\u0028\u0029",
            "name": "sendCommand",
            "summary": "Send\u0020and\u0020execute\u0020command\u0020asynchronously",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-Bus.html#method_sendCommand"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\Bus\u003A\u003ApublishEvent\u0028\u0029",
            "name": "publishEvent",
            "summary": "Send\u0020event\u0020which\u0020will\u0020be\u0020handled\u0020asynchronously",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-Bus.html#method_publishEvent"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\Bus\u003A\u003AraiseEvent\u0028\u0029",
            "name": "raiseEvent",
            "summary": "Send\u0020event\u0020which\u0020will\u0020be\u0020handled\u0020synchronously",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-Bus.html#method_raiseEvent"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\Bus\u003A\u003AlogNew\u0028\u0029",
            "name": "logNew",
            "summary": "Log\u0020new\u0020bus\u0020object",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-Bus.html#method_logNew"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\Bus\u003A\u003AlogDone\u0028\u0029",
            "name": "logDone",
            "summary": "Log\u0020executed\u0020bus\u0020object",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-Bus.html#method_logDone"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\Bus\u003A\u003AlogFailed\u0028\u0029",
            "name": "logFailed",
            "summary": "Log\u0020failed\u0020bus\u0020object\u0020execution",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-Bus.html#method_logFailed"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusHandler",
            "name": "BusHandler",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusHandler.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusHandler\u003A\u003AhandleObject\u0028\u0029",
            "name": "handleObject",
            "summary": "Handle\u0020the\u0020job",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusHandler.html#method_handleObject"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusHandler\u003A\u003AhandleObjectExecution\u0028\u0029",
            "name": "handleObjectExecution",
            "summary": "Entry\u0020point\u0020of\u0020object\u0020handling\u0020execution",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusHandler.html#method_handleObjectExecution"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusHandler\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Execute\u0020the\u0020command\u0020or\u0020event\u0020body",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusHandler.html#method_execute"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusHandler\u003A\u003AsetTypedObject\u0028\u0029",
            "name": "setTypedObject",
            "summary": "Sets\u0020generic\u0020bus\u0020object\u0020as\u0020the\u0020specific\u0020typed\u0020object\u0020managed\u0020by\u0020the\u0020handler",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusHandler.html#method_setTypedObject"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusHandler\u003A\u003Afailed\u0028\u0029",
            "name": "failed",
            "summary": "Sets\u0020handling\u0020definitely\u0020failed\nMust\u0020be\u0020public\u0020because\u0020can\u0020be\u0020called\u0020from\u0020outside\u0020scope\u0020\u0028by\u0020Laravel\u0029",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusHandler.html#method_failed"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusHandler\u003A\u003AnotifyFailures\u0028\u0029",
            "name": "notifyFailures",
            "summary": "Manage\u0020the\u0020failed\u0020handling.",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusHandler.html#method_notifyFailures"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusHandler\u003A\u003AisJob\u0028\u0029",
            "name": "isJob",
            "summary": "Detects\u0020if\u0020handling\u0020a\u0020Laravel\u0020Job",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusHandler.html#method_isJob"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusHandler\u003A\u003A\u0024busObject",
            "name": "busObject",
            "summary": "\u007B\u0040see\u0020Command\u007D\u0020or\u0020\u007B\u0040see\u0020Event\u007D\u0020to\u0020handle",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusHandler.html#property_busObject"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusHandler\u003A\u003A\u0024maxRetries",
            "name": "maxRetries",
            "summary": "Maximum\u0020retries\u0020if\u0020handling\u0020fails",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusHandler.html#property_maxRetries"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusHandler\u003A\u003A\u0024isActive",
            "name": "isActive",
            "summary": "Defines\u0020if\u0020handling\u0020is\u0020active,\u0020used\u0020by\u0020retries\u0020algorithm",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusHandler.html#property_isActive"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusObject",
            "name": "BusObject",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusObject.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusObject\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Object\u0020constructor\u0020setting\u0020\u007B\u0040see\u0020id\u007D\u0020and\u0020\u007B\u0040see\u0020correlationId\u007D",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusObject.html#method___construct"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusObject\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Getter\u0020for\u0020parent\u0020properties",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusObject.html#method___get"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusObject\u003A\u003A__set\u0028\u0029",
            "name": "__set",
            "summary": "Setter\u0020for\u0020parent\u0020properties",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusObject.html#method___set"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusObject\u003A\u003Aclone\u0028\u0029",
            "name": "clone",
            "summary": "Clone\u0020the\u0020object\u0020with\u0020a\u0020new\u0020\u007B\u0040see\u0020id\u007D",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusObject.html#method_clone"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusObject\u003A\u003Apayload\u0028\u0029",
            "name": "payload",
            "summary": "Encodes\u0020props\u0020as\u0020json\u0020string",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusObject.html#method_payload"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusObject\u003A\u003Aname\u0028\u0029",
            "name": "name",
            "summary": "Gets\u0020bus\u0020object\u0020name",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusObject.html#method_name"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusObject\u003A\u003Aclass\u0028\u0029",
            "name": "class",
            "summary": "Gets\u0020bus\u0020object\u0020class\u0020name",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusObject.html#method_class"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusObject\u003A\u003AhandlerName\u0028\u0029",
            "name": "handlerName",
            "summary": "Gets\u0020bus\u0020object\u0020handler\u0020name",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusObject.html#method_handlerName"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusObject\u003A\u003Aprops\u0028\u0029",
            "name": "props",
            "summary": "Gets\u0020props\u0020list",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusObject.html#method_props"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusObject\u003A\u003AassignNewId\u0028\u0029",
            "name": "assignNewId",
            "summary": "Sets\u0020\u007B\u0040see\u0020id\u007D",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusObject.html#method_assignNewId"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusObject\u003A\u003A\u0024id",
            "name": "id",
            "summary": "Bus\u0020object\u0020id",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusObject.html#property_id"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusObject\u003A\u003A\u0024correlationId",
            "name": "correlationId",
            "summary": "Id\u0020for\u0020bus\u0020object\u0020correlation",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusObject.html#property_correlationId"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\BusObject\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "Connection\u0020name,\u0020required\u0020by\u0020Laravel",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-BusObject.html#property_connection"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\IBusObject",
            "name": "IBusObject",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-IBusObject.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\IBusObject\u003A\u003Aname\u0028\u0029",
            "name": "name",
            "summary": "Gets\u0020bus\u0020object\u0020name",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-IBusObject.html#method_name"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\IBusObject\u003A\u003AhandlerName\u0028\u0029",
            "name": "handlerName",
            "summary": "Gets\u0020bus\u0020object\u0020handler\u0020name",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-IBusObject.html#method_handlerName"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\IBusObject\u003A\u003Aclass\u0028\u0029",
            "name": "class",
            "summary": "Gets\u0020bus\u0020object\u0020class\u0020name",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-IBusObject.html#method_class"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\IBusObject\u003A\u003Aprops\u0028\u0029",
            "name": "props",
            "summary": "Gets\u0020props\u0020list",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-IBusObject.html#method_props"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\IBusObject\u003A\u003Apayload\u0028\u0029",
            "name": "payload",
            "summary": "Encodes\u0020props\u0020as\u0020json\u0020string",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-IBusObject.html#method_payload"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus\\IBusObject\u003A\u003Aclone\u0028\u0029",
            "name": "clone",
            "summary": "Clone\u0020the\u0020object\u0020with\u0020a\u0020new\u0020\u007B\u0040see\u0020id\u007D",
            "url": "classes/Alangiacomin-LaravelBasePack-Bus-IBusObject.html#method_clone"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\CommandHandlers\\AggregateCommandHandler",
            "name": "AggregateCommandHandler",
            "summary": "The\u0020command\u0020to\u0020be\u0020handled",
            "url": "classes/Alangiacomin-LaravelBasePack-CommandHandlers-AggregateCommandHandler.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\CommandHandlers\\AggregateCommandHandler\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Execute\u0020the\u0020command",
            "url": "classes/Alangiacomin-LaravelBasePack-CommandHandlers-AggregateCommandHandler.html#method_execute"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\CommandHandlers\\AggregateCommandHandler\u003A\u003Aapply\u0028\u0029",
            "name": "apply",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-CommandHandlers-AggregateCommandHandler.html#method_apply"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\CommandHandlers\\AggregateCommandHandler\u003A\u003AreadAggregate\u0028\u0029",
            "name": "readAggregate",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-CommandHandlers-AggregateCommandHandler.html#method_readAggregate"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\CommandHandlers\\CommandHandler",
            "name": "CommandHandler",
            "summary": "The\u0020command\u0020to\u0020be\u0020handled",
            "url": "classes/Alangiacomin-LaravelBasePack-CommandHandlers-CommandHandler.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\CommandHandlers\\CommandHandler\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Command\u0020constructor",
            "url": "classes/Alangiacomin-LaravelBasePack-CommandHandlers-CommandHandler.html#method___construct"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\CommandHandlers\\CommandHandler\u003A\u003Apublish\u0028\u0029",
            "name": "publish",
            "summary": "Publish\u0020event\u0020on\u0020the\u0020bus",
            "url": "classes/Alangiacomin-LaravelBasePack-CommandHandlers-CommandHandler.html#method_publish"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\CommandHandlers\\CommandHandler\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020the\u0020\u007B\u0040see\u0020Command\u007D",
            "url": "classes/Alangiacomin-LaravelBasePack-CommandHandlers-CommandHandler.html#method_handle"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\CommandHandlers\\CommandHandler\u003A\u003AgetResult\u0028\u0029",
            "name": "getResult",
            "summary": "Gets\u0020default\u0020result,\u0020overridable",
            "url": "classes/Alangiacomin-LaravelBasePack-CommandHandlers-CommandHandler.html#method_getResult"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Commands\\AggregateCommand",
            "name": "AggregateCommand",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Commands-AggregateCommand.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Commands\\AggregateCommand\u003A\u003A\u0024aggregateId",
            "name": "aggregateId",
            "summary": "Aggregate\u0020ID",
            "url": "classes/Alangiacomin-LaravelBasePack-Commands-AggregateCommand.html#property_aggregateId"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Commands\\Command",
            "name": "Command",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Commands-Command.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Commands\\ICommand",
            "name": "ICommand",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Commands-ICommand.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateCommand",
            "name": "CreateCommand",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateCommand.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020command\u0020instance.",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateCommand.html#method___construct"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateCommand\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Execute\u0020the\u0020console\u0020command.",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateCommand.html#method_handle"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateCommand\u003A\u003AcreateCommandFile\u0028\u0029",
            "name": "createCommandFile",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateCommand.html#method_createCommandFile"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateCommand\u003A\u003AcreateCommandHandlerFile\u0028\u0029",
            "name": "createCommandHandlerFile",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateCommand.html#method_createCommandHandlerFile"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateCommand\u003A\u003AstubReplace\u0028\u0029",
            "name": "stubReplace",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateCommand.html#method_stubReplace"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateCommand\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "The\u0020name\u0020and\u0020signature\u0020of\u0020the\u0020console\u0020command.",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateCommand.html#property_signature"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateCommand\u003A\u003A\u0024description",
            "name": "description",
            "summary": "The\u0020console\u0020command\u0020description.",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateCommand.html#property_description"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateEvent",
            "name": "CreateEvent",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateEvent.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateEvent\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020command\u0020instance.",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateEvent.html#method___construct"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateEvent\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Execute\u0020the\u0020console\u0020command.",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateEvent.html#method_handle"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateEvent\u003A\u003AcreateEventFile\u0028\u0029",
            "name": "createEventFile",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateEvent.html#method_createEventFile"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateEvent\u003A\u003AcreateEventHandlerFile\u0028\u0029",
            "name": "createEventHandlerFile",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateEvent.html#method_createEventHandlerFile"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateEvent\u003A\u003AstubReplace\u0028\u0029",
            "name": "stubReplace",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateEvent.html#method_stubReplace"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateEvent\u003A\u003A\u0024signature",
            "name": "signature",
            "summary": "The\u0020name\u0020and\u0020signature\u0020of\u0020the\u0020console\u0020command.",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateEvent.html#property_signature"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands\\CreateEvent\u003A\u003A\u0024description",
            "name": "description",
            "summary": "The\u0020console\u0020command\u0020description.",
            "url": "classes/Alangiacomin-LaravelBasePack-Console-Commands-CreateEvent.html#property_description"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Controllers\\Controller",
            "name": "Controller",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Controllers-Controller.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Controllers\\Controller\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Execute\u0020\u007B\u0040see\u0020Command\u007D\u0020over\u0020the\u0020bus",
            "url": "classes/Alangiacomin-LaravelBasePack-Controllers-Controller.html#method_execute"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Controllers\\Controller\u003A\u003AsendCommand\u0028\u0029",
            "name": "sendCommand",
            "summary": "Send\u0020\u007B\u0040see\u0020Command\u007D\u0020on\u0020the\u0020bus",
            "url": "classes/Alangiacomin-LaravelBasePack-Controllers-Controller.html#method_sendCommand"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Core\\Enums\\BindingType",
            "name": "BindingType",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Core-Enums-BindingType.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Core\\Enums\\BindingType\u003A\u003ABind",
            "name": "Bind",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Core\\Enums\\BindingType\u003A\u003ASingleton",
            "name": "Singleton",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\EventHandlers\\EventHandler",
            "name": "EventHandler",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-EventHandlers-EventHandler.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\EventHandlers\\EventHandler\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020the\u0020\u007B\u0040see\u0020Event\u007D",
            "url": "classes/Alangiacomin-LaravelBasePack-EventHandlers-EventHandler.html#method_handle"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\EventHandlers\\EventHandler\u003A\u003AsendCommand\u0028\u0029",
            "name": "sendCommand",
            "summary": "Push\u0020command\u0020on\u0020the\u0020bus",
            "url": "classes/Alangiacomin-LaravelBasePack-EventHandlers-EventHandler.html#method_sendCommand"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\EventHandlers\\EventHandler\u003A\u003AshouldQueue\u0028\u0029",
            "name": "shouldQueue",
            "summary": "Defines\u0020if\u0020the\u0020event\u0020job\u0020must\u0020be\u0020queued\u0020or\u0020ignored",
            "url": "classes/Alangiacomin-LaravelBasePack-EventHandlers-EventHandler.html#method_shouldQueue"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Events\\Event",
            "name": "Event",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Events-Event.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Events\\Event\u003A\u003AbroadcastAs\u0028\u0029",
            "name": "broadcastAs",
            "summary": "The\u0020event\u0027s\u0020broadcast\u0020name",
            "url": "classes/Alangiacomin-LaravelBasePack-Events-Event.html#method_broadcastAs"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Events\\IEvent",
            "name": "IEvent",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Events-IEvent.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Facades\\LaravelBasePackFacade",
            "name": "LaravelBasePackFacade",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Facades-LaravelBasePackFacade.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Facades\\LaravelBasePackFacade\u003A\u003AgetFacadeAccessor\u0028\u0029",
            "name": "getFacadeAccessor",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Facades-LaravelBasePackFacade.html#method_getFacadeAccessor"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\LaravelBasePack",
            "name": "LaravelBasePack",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-LaravelBasePack.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\LaravelBasePack\u003A\u003AcallWithInjection\u0028\u0029",
            "name": "callWithInjection",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-LaravelBasePack.html#method_callWithInjection"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\LaravelBasePack\u003A\u003AcheckObjectType\u0028\u0029",
            "name": "checkObjectType",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-LaravelBasePack.html#method_checkObjectType"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\LaravelBasePack\u003A\u003AcheckObject\u0028\u0029",
            "name": "checkObject",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-LaravelBasePack.html#method_checkObject"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\LaravelBasePackServiceProvider",
            "name": "LaravelBasePackServiceProvider",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-LaravelBasePackServiceProvider.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\LaravelBasePackServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020any\u0020application\u0020services.",
            "url": "classes/Alangiacomin-LaravelBasePack-LaravelBasePackServiceProvider.html#method_register"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\LaravelBasePackServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020package\u0020services.",
            "url": "classes/Alangiacomin-LaravelBasePack-LaravelBasePackServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Middleware\\CommandResult",
            "name": "CommandResult",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Middleware-CommandResult.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Middleware\\CommandResult\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "JsonMiddleware\u0020constructor.",
            "url": "classes/Alangiacomin-LaravelBasePack-Middleware-CommandResult.html#method___construct"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Middleware\\CommandResult\u003A\u003Ahandle\u0028\u0029",
            "name": "handle",
            "summary": "Handle\u0020an\u0020incoming\u0020request.",
            "url": "classes/Alangiacomin-LaravelBasePack-Middleware-CommandResult.html#method_handle"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Middleware\\CommandResult\u003A\u003AgetResponseContent\u0028\u0029",
            "name": "getResponseContent",
            "summary": "Gets\u0020the\u0020response\u0020content\u0020as\u0020decoded\u0020json\u0020or\u0020original\u0020value",
            "url": "classes/Alangiacomin-LaravelBasePack-Middleware-CommandResult.html#method_getResponseContent"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Middleware\\CommandResult\u003A\u003A\u0024response",
            "name": "response",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Middleware-CommandResult.html#property_response"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Middleware\\CommandResult\u003A\u003A\u0024factory",
            "name": "factory",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Middleware-CommandResult.html#property_factory"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Models\\Aggregate",
            "name": "Aggregate",
            "summary": "Aggregate\u0020root",
            "url": "classes/Alangiacomin-LaravelBasePack-Models-Aggregate.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Models\\Aggregate\u003A\u003Araise\u0028\u0029",
            "name": "raise",
            "summary": "Raise\u0020aggregate\u0020event",
            "url": "classes/Alangiacomin-LaravelBasePack-Models-Aggregate.html#method_raise"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Models\\Aggregate\u003A\u003A\u0024events",
            "name": "events",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Models-Aggregate.html#property_events"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Models\\IAggregate",
            "name": "IAggregate",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Models-IAggregate.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Models\\IAggregate\u003A\u003Araise\u0028\u0029",
            "name": "raise",
            "summary": "Raise\u0020aggregate\u0020event",
            "url": "classes/Alangiacomin-LaravelBasePack-Models-IAggregate.html#method_raise"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Providers\\EventServiceProvider",
            "name": "EventServiceProvider",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Providers-EventServiceProvider.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Providers\\EventServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Register\u0020any\u0020events\u0020for\u0020your\u0020application.",
            "url": "classes/Alangiacomin-LaravelBasePack-Providers-EventServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Providers\\EventServiceProvider\u003A\u003AshouldDiscoverEvents\u0028\u0029",
            "name": "shouldDiscoverEvents",
            "summary": "Determine\u0020if\u0020events\u0020and\u0020listeners\u0020should\u0020be\u0020automatically\u0020discovered.",
            "url": "classes/Alangiacomin-LaravelBasePack-Providers-EventServiceProvider.html#method_shouldDiscoverEvents"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Providers\\EventServiceProvider\u003A\u003AdiscoverEventsWithin\u0028\u0029",
            "name": "discoverEventsWithin",
            "summary": "Get\u0020the\u0020listener\u0020directories\u0020that\u0020should\u0020be\u0020used\u0020to\u0020discover\u0020events.",
            "url": "classes/Alangiacomin-LaravelBasePack-Providers-EventServiceProvider.html#method_discoverEventsWithin"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Providers\\RepositoryServiceProvider",
            "name": "RepositoryServiceProvider",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Providers-RepositoryServiceProvider.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Providers\\RepositoryServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020repository\u0020bindings",
            "url": "classes/Alangiacomin-LaravelBasePack-Providers-RepositoryServiceProvider.html#method_register"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Repositories\\IRepository",
            "name": "IRepository",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Repositories-IRepository.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Repositories\\IUserRepository",
            "name": "IUserRepository",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Repositories-IUserRepository.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Repositories\\Repository",
            "name": "Repository",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Repositories-Repository.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Repositories\\UserRepository",
            "name": "UserRepository",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Repositories-UserRepository.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Repositories\\UserRepository\u003A\u003AuserPermissions\u0028\u0029",
            "name": "userPermissions",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Repositories-UserRepository.html#method_userPermissions"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Repositories\\UserRepository\u003A\u003AuserDirectPermissions\u0028\u0029",
            "name": "userDirectPermissions",
            "summary": "",
            "url": "classes/Alangiacomin-LaravelBasePack-Repositories-UserRepository.html#method_userDirectPermissions"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Bus",
            "name": "Bus",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-bus.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\CommandHandlers",
            "name": "CommandHandlers",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-commandhandlers.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Commands",
            "name": "Commands",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-commands.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console\\Commands",
            "name": "Commands",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-console-commands.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Console",
            "name": "Console",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-console.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-controllers.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Core\\Enums",
            "name": "Enums",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-core-enums.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Core",
            "name": "Core",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-core.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\EventHandlers",
            "name": "EventHandlers",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-eventhandlers.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Events",
            "name": "Events",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-events.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Facades",
            "name": "Facades",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-facades.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack",
            "name": "LaravelBasePack",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack.html"
        },                {
            "fqsen": "\\Alangiacomin",
            "name": "Alangiacomin",
            "summary": "",
            "url": "namespaces/alangiacomin.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Middleware",
            "name": "Middleware",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-middleware.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-models.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-providers.html"
        },                {
            "fqsen": "\\Alangiacomin\\LaravelBasePack\\Repositories",
            "name": "Repositories",
            "summary": "",
            "url": "namespaces/alangiacomin-laravelbasepack-repositories.html"
        }            ]
);
