# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
    - name: Checkout
      uses: actions/checkout@v2.4.0
      with:
        ref: gh-pages
      
    - name: Merge without commit
      run: git merge develop --no-commit --no-ff --allow-unrelated-histories
      
    - name: Generate docs
      run: php .\phpDocumentor.phar
      
    - name: Abort merge
      run: git merge --abort
      
    - name: Add all files
      run: git add .
      
    - name: Commit
      run: git commit -m "docs"
      
